language: node_js
node_js:
  - "16"

cache:
  npm: true
  directories:
    - node_modules

addons:
  chrome: stable

before_install:
  - npm config set progress false

install:
  - npm ci --verbose

script:
  - npm run test -- --watch=false --browsers=ChromeHeadlessNoSandbox

notifications:
  email:
    on_success: never
    on_failure: always
